---
baseURL: https://example.com
languageCode: en-us
title: Yourfolio Theme
theme: yourfolio
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
googleAnalytics: UA-XXXXX-Y
menu:
  main:
  - url: "/contact"
    name: Contact
    weight: 2
  - url: "/about"
    name: About
    weight: 1
params:
  env: development
  logoImage: img/logo.png
  logoImageAlt: Yourfolio Theme brand logo
